title: Simplify.Web
description: Simplify.Web is an open-source, lightweight and fast server-side .NET web-framework based on ASP.NET Core for building HTTP based web-applications, RESTful APIs etc.

baseurl: ""
url: "https://web.simplifynet.dev"
repository: "SimplifyNet/Simplify.Web"

simplify_web_repository_url: "https://github.com/SimplifyNet/Simplify.Web"
templates_repository_url: "https://github.com/SimplifyNet/Simplify.Web.Templates"

simplify_url: "https://simplifynet.dev"

markdown: kramdown
theme: jekyll-theme-midnight
